image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "15 2017"
    - VSVERSION: "14 2015"
    - VSVERSION: "12 2013"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

matrix:
  exclude:
    - VSVERSION: "12 2013"
      platform: x64
    - VSVERSION: "12 2013"
      configuration: Debug

init:
  - cmake --version
  - msbuild /version

before_build:
  - if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION%" )
  - if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION% Win64")
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: "build\\winflexbison.sln"
  parallel: false
